# Generated by Django 3.2.4 on 2021-09-06 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='c_code',
            fields=[
                ('c_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.TextField()),
            ],
        ),
    ]
